name: Deploy Subscriber Service

on:
  push:
    branches: [ main ]
    paths:
      - 'service2/**'
      - '.github/workflows/service2-deploy.yml'
  workflow_dispatch:

env:
  PROJECT_ID: gcp-pubsub-456020
  REGION: us-central1
  SERVICE_NAME: pubsub-subscriber

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4

    - id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Deploy
      working-directory: ./service2
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars="PUBSUB_PROJECT_ID=$PROJECT_ID" 